// Generated by Cap'n Proto compiler, DO NOT EDIT
// source: stream.capnp

#pragma once

#include "export-capnp.h"
#include <capnp/generated-header-support.h>
#include <kj/windows-sanity.h>

#ifndef CAPNP_VERSION
#error "CAPNP_VERSION is not defined, is capnp/generated-header-support.h missing?"
#elif CAPNP_VERSION != 1005000
#error "Version mismatch between generated code and library headers.  You must use the same version of the Cap'n Proto compiler and library."
#endif


CAPNP_BEGIN_HEADER

namespace capnp {
namespace schemas {

CAPNP_DECLARE_SCHEMA(995f9a3377c0b16e);

}  // namespace schemas
}  // namespace capnp

namespace capnp {

struct CAPNP_CLASS StreamResult {
  StreamResult() = delete;

  class Reader;
  class Builder;
  class Pipeline;

  struct _capnpPrivate {
    CAPNP_DECLARE_STRUCT_HEADER(995f9a3377c0b16e, 0, 0)
    #if !CAPNP_LITE
    static constexpr ::capnp::_::RawBrandedSchema const* brand() { return &schema->defaultBrand; }
    #endif  // !CAPNP_LITE
  };
};

// =======================================================================================

class CAPNP_CLASS StreamResult::Reader {
public:
  typedef StreamResult Reads;

  CAPNP_API Reader() = default;
  CAPNP_API inline explicit Reader(::capnp::_::StructReader base): _reader(base) {}

  CAPNP_API inline ::capnp::MessageSize totalSize() const {
    return _reader.totalSize().asPublic();
  }

#if !CAPNP_LITE
  CAPNP_API inline ::kj::StringTree toString() const {
    return ::capnp::_::structString(_reader, *_capnpPrivate::brand());
  }
#endif  // !CAPNP_LITE

private:
  ::capnp::_::StructReader _reader;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::List;
  friend class ::capnp::MessageBuilder;
  friend class ::capnp::Orphanage;
};

class CAPNP_CLASS StreamResult::Builder {
public:
  typedef StreamResult Builds;

  Builder() = delete;  // Deleted to discourage incorrect usage.
                       // You can explicitly initialize to nullptr instead.
  CAPNP_API inline Builder(decltype(nullptr)) {}
  CAPNP_API inline explicit Builder(::capnp::_::StructBuilder base): _builder(base) {}
  CAPNP_API inline operator Reader() const { return Reader(_builder.asReader()); }
  CAPNP_API inline Reader asReader() const { return *this; }

  CAPNP_API inline ::capnp::MessageSize totalSize() const { return asReader().totalSize(); }
#if !CAPNP_LITE
  CAPNP_API inline ::kj::StringTree toString() const { return asReader().toString(); }
#endif  // !CAPNP_LITE

private:
  ::capnp::_::StructBuilder _builder;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
  friend class ::capnp::Orphanage;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::_::PointerHelpers;
};

#if !CAPNP_LITE
class CAPNP_CLASS StreamResult::Pipeline {
public:
  typedef StreamResult Pipelines;

  CAPNP_API inline Pipeline(decltype(nullptr)): _typeless(nullptr) {}
  CAPNP_API inline explicit Pipeline(::capnp::AnyPointer::Pipeline&& typeless)
      : _typeless(kj::mv(typeless)) {}

private:
  ::capnp::AnyPointer::Pipeline _typeless;
  friend class ::capnp::PipelineHook;
  template <typename, ::capnp::Kind>
  friend struct ::capnp::ToDynamic_;
};
#endif  // !CAPNP_LITE

// =======================================================================================

}  // namespace

CAPNP_END_HEADER

